apiVersion: apps/v1
kind: Deployment
metadata:
  name: appservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appservice
  template:
    metadata:
      labels:
        name: appservice
    spec:
      serviceAccountName: appservice
      containers:
        - name: appservice
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - appservice
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "appservice"
